use teamspeak autorename of used nickname
planetteamspeak/ts3phpframework pull request #153
Opened 2020-10-25 22:32 UTC by Fabiryn

Fixes an issue, when the nickname of the query is already in use. 
The Teamspeak3::factory throws an error and doesn't return the adapter object. Unfortunately, the script keeps connected until the process exits. 

Apparently teamspeak auto renamed the query and appended a 1 (Bot -> Bot1).
With the try catch it uses the auto rename and proceeds with the rest of the factory calls.

2020-10-25 23:05 UTC, ronindesign requested changes
Silently catching the exception and continuing on when the application expects `client_nickname` to equal `$this->predfined_query_name` will result in undefined behavior.

Let's try catching the exception and throwing something fatal. We certainly don't want the application to continue on if it's configured to have `client_nickname`, e.g. _Bot_, but actually has some other, dynamic name, e.g. _Bot1_, _Bot2_, ..., _BotN_.

The `if` statement is for some fault tolerance to try and update the nickname if for some reason it's not correct. So if it's unable to do so, we need to throw a fatal exception. Would this work for you?

```php
catch (Exception $e) {
  throw new TeamSpeak3_Adapter_ServerQuery_Exception("nickname is already in use", 0x201);
}
```
Error id ref:
```
normal | client_nickname_inuse | 0x0201 | 513 | nickname is already in use
```
As per: https://forum.teamspeak.com/threads/102276-Server-query-error-id-list?s=268a856f7027838f436aa386e5abb2ea&p=388143#post388143
> All possible errors are listed in public_errors.h and public_errors_rare.h located in the PluginSDK download, which is also where the above list originally came from. Column 4 is just the decimal expression of the hex number and the 5th one is just the error message assigned to it as returned by the ts3Functions.getErrorMessage function.

2020-10-25 23:55 UTC, Fabiryn commented
It already throws the 513 error code. But somehow the connection keeps open. The factory throws and I don't have access to the current (still open) node object.

So in my case, I try to connect the query with the name "Bot"
-> error 513 nickname is already in use
-> Bot1 is still connected as a active serverquery

-> own try catch wrapper tries to handle nickname error
-> try to connect with Bot1
-> error 513 nickname already in use
...

Is there a way to kill the the open connection if it throws inside the factory?

2020-10-26 01:13 UTC, ronindesign commented
Ah I see. Yes, it's possible clean exit logic has not been implemented for this yet. Ideally, the framework should let the exception bubble up to the top, catch it, send disconnect/exit message to ts3server as needed, then finally re-throw the fatal exception and exit.

It looks like we have the adapter clean-up already in `TeamSpeak3_Adapter_ServerQuery::__destruct()`. So let's try a try/catch around the main setup in `TeamSpeak3::factory`:
```php
    $object = new $adapter($options);
    try {
      if($object instanceof TeamSpeak3_Adapter_ServerQuery)
      {
        $node = $object->getHost();

        if($uri->hasUser() && $uri->hasPass())
        {
          $node->login($uri->getUser(), $uri->getPass());
        }
...
          elseif($uri->hasQueryVar("client_name"))
          {
            $node = $node->clientGetByName($uri->getQueryVar("client_name"));
          }
        }
          elseif($uri->hasQueryVar("client_name"))
          {
            $node = $node->clientGetByName($uri->getQueryVar("client_name"));
          }
        }

        return $node;
      }
    } catch (Exception $e) {
      unset($object);
      throw $e;
    }

    return $object;
  }
```

`unset($object)` should call `TeamSpeak3_Adapter_ServerQuery::__destruct()` resulting in correct server query exit request and clean up. Would you mind testing the above code with your case and see if it exits with fatal error and correctly disconnects the framework from the ts3server?

2020-10-26 08:08 UTC, Fabiryn commented
no problem - I will test it tonight

2020-10-26 16:59 UTC, Fabiryn commented
Hey, I tried your code, unfortunately the __destructor isn’t called with the unset of $object or $node. 
Seems like there is still an active reference to that object. I’m not sure how php is handling the garbage collection.

The only thing that works for me, is directly calling `$node->request("quit");`
```
$object = new $adapter($options);

try {
  if($object instanceof TeamSpeak3_Adapter_ServerQuery)
  {
    $node = $object->getHost();

    if($uri->hasUser() && $uri->hasPass())
    {
      $node->login($uri->getUser(), $uri->getPass());
    }
...
      elseif($uri->hasQueryVar("client_name"))
      {
        $node = $node->clientGetByName($uri->getQueryVar("client_name"));
      }
    }

    return $node;
  }
}
catch (Exception $e) {
  try
  {
    $node->request("quit");
  }
  catch(Exception $e)
  {
    return;
  }
  unset($object, $node);
  throw $e;
}
```

2020-10-26 18:25 UTC, ronindesign commented
Does calling the deconstructor directly work? If it does, let's go that route and I'll get this merged in right away.

```php
    $object = new $adapter($options);

    try {
      if($object instanceof TeamSpeak3_Adapter_ServerQuery)
      {
        $node = $object->getHost();

        if($uri->hasUser() && $uri->hasPass())
        {
          $node->login($uri->getUser(), $uri->getPass());
        }
...
          elseif($uri->hasQueryVar("client_name"))
          {
            $node = $node->clientGetByName($uri->getQueryVar("client_name"));
          }
        }
          elseif($uri->hasQueryVar("client_name"))
          {
            $node = $node->clientGetByName($uri->getQueryVar("client_name"));
          }
        }

        return $node;
      }
    } catch (Exception $e) {
      $object->__destruct();
      throw $e;
    }

    return $object;
  }
```

2020-10-26 18:50 UTC, Fabiryn commented
that works. thanks for the quick help.

2020-10-26 21:44 UTC, Fabiryn commented
sorry clicked on the wrong icon

2020-10-26 22:30 UTC, ronindesign commented
You're welcome! I'll review this shortly and merge it. Thanks for the follow-up, working through the PR with me, and testing it, really appreciate it!

2020-10-28 03:57 UTC, merged